spring:
  application:
    name: purchase-order-workflow
  datasource:
    url: jdbc:postgresql://localhost:5432/purchase_order_workflow
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    cache:
      type: simple

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
